### ISSUE TITLE
Dont make updates so fast!

### ISSUE THREAD

**Issue by enescaglayan** [AlanFinotty1995/AAFRealtekMod#1]
Okay thanks for these drivers, i love them but... You should stop making updates fast, i have limited internet connection and i dont want download the drivers here everyday! you should make updates every week or every month. If you dont want just make a application that checks for updates and downloads emergency updates if not download it every week.

**Comment by AlanFinotty1995** [comment]
> 
> 
> Okay thanks for these drivers, i love them but... You should stop making updates fast, i have limited internet connection and i dont want download the drivers here everyday! you should make updates every week or every month. If you dont want just make a application that checks for updates and downloads emergency updates if not download it every week.

But the intention is to always keep the latest version, along with bug fixes, to achieve as much compatibility as possible. You do not need to download the latest version as it is released. If you installed one of these versions and it is going well, keep it as it is. Leave to update, perhaps, monthly or fortnightly.
