### ISSUE TITLE
Not compatible with ALC889?

### ISSUE THREAD

**Issue by Paul17041993** [AlanFinotty1995/AAFRealtekMod#12]
I did a basic install with only the drivers and dolby atmos, on an old gigabyte board with the ALC889, but when the AAF driver is installed to the device it code-10's; "requested operation unsuccessful"

**Comment by AlanFinotty1995** [comment]
Yeah. I identified here in INF some registry entries that are probably the problem. I am correcting it and will soon launch a new driver package. Kind regards. Thanks for the feedback.

**Comment by AlanFinotty1995** [comment]
To recap, this mod is compatible with Windows 7, 8, 8.1 and 10.
