### ISSUE TITLE
6.0.8888.1 - W10 1909 - No effects works

### ISSUE THREAD

**Issue by apk1995apk** [AlanFinotty1995/AAFRealtekMod#16]
Thanks for mod !
Everything installs perfectly but nothing is changed in audio. No effects work. (Atmos/Nahimic/BlasterX)

![Capture](https://user-images.githubusercontent.com/10492511/73607389-803f2e00-45db-11ea-9b8d-f7c66957e56e.PNG)

Release -  6.0.8888.1
OS - W10 1909 (Tried with Developer mode as well)
Chipset Realtek ALC892
Stereo Output Jack

**Comment by AlanFinotty1995** [comment]
This also depends on your audio chip's standard policies. Do the following:

1 - Open the same tool as the image you posted;
2 - Search for "RunningOnWindows8point1";
3 - When you find it, check the set where this value is present (DrvCtrl ??), but DO NOT check the value;
4 - Click "Save" to save the changes and restart your computer.

See if it works.

**Comment by Dark4Codrutz** [comment]
How do I load the RTKHDAUD.dat file ? have it but can't seem to figure out the program load function

**Comment by Dark4Codrutz** [comment]
![image](https://user-images.githubusercontent.com/18706363/73618635-48f76e00-4629-11ea-86f8-218a5df39f0c.png)

So I have mine on Ctrl17 but my value is checked. Should I disable it ?
Also, on the saving part.. the RTKHDAUD writing starts flashing red as to suggest file not loaded.
Should I've installed on top of working realtek hd audio driver ?

**Comment by AlanFinotty1995** [comment]
Uncheck "RunningOnWindows8point1", click Save at the top and restart your PC.

**Comment by Dark4Codrutz** [comment]
Before I can save I need to load the .day file which is not loaded, just
like the OP here

**Comment by apk1995apk** [comment]
> This also depends on your audio chip's standard policies. Do the following:
> 
> 1 - Open the same tool as the image you posted and click on the "Driver Policy" tab;
> 2 - Search for "RunningOnWindows8point1";
> 3 - When you find it, check the set where this value is present (DrvCtrl ??), but DO NOT check the value;
> 4 - Click "Save" to save the changes and restart your computer.
> 
> Follow the image below as an example:
> 
> ![Config](https://user-images.githubusercontent.com/48844235/73611255-b15d3580-45be-11ea-9e92-d72cac4774d9.jpg)
> 
> See if it works.

This got everything working. Thanks a lot Alan !
