### ISSUE TITLE
Unable to select 5.1 after installing the driver

### ISSUE THREAD

**Issue by devedse** [AlanFinotty1995/AAFRealtekMod#2]
Hi @AlanFinotty1995 ,

I got forwarded to your github page by someone in this thread :smile::
https://www.techpowerup.com/forums/threads/unlocked-realtek-hd-audio-drivers-windows-7-8-with-dolby-digital-live-and-dts-interactive.193148/page-119#post-4007702

According to his post your modded driver should be able to fix the issue where I couldn't play 5.1 surround audio over my Optical S/PDIF cable. 😲 

However, after installing the driver the option is sadly still disabled:
![image](https://user-images.githubusercontent.com/2350015/69290707-09f87580-0c01-11ea-9418-686afcfef490.png)

Am I doing something wrong :smile:?

My PC specs:
```
CPU: Ryzen 2700x
Mobo: Gigabyte Aorus X570 ULTRA
```

**Comment by AlanFinotty1995** [comment]
You must follow the steps at the end of this post:
https://www.techpowerup.com/forums/threads/realtek-ultimate-audio-driver-mod-for-win7-win8-win8-1-win10.250915/post-3965663

You will see the spoilers **"HOW TO ACTIVATE DOLBY DIGITAL LIVE"** and **"HOW TO ACTIVATE DTS INTERACTIVE"**

**Comment by AlanFinotty1995** [comment]
In a few days, I will make a video showing exactly how to enable Dolby Digital Live or DTS Interactive for those users who encounter difficulties.

**Comment by devedse** [comment]
Ah thanks for the quick response. I'll try this tonight!

**Comment by devedse** [comment]
It works!

You've done an amazing job!

**Comment by AlanFinotty1995** [comment]
I'm glad it worked. Enjoy it.
