### ISSUE TITLE
Everything is working except SB Connect 2

### ISSUE THREAD

**Issue by miaachan** [AlanFinotty1995/AAFRealtekMod#23]
Hi Dev,
Thanks for your effort on the Realtekmod! My motherboard is X470 Ultragaming with ALC1220, I am currently using the latest version (6.0.8900.1). Everything like Dolby, Nahimic is working well, except the SB Connect 2 shows a black screen with "cannot detect audio devices" error.

Things I've tried:
1. Uninstall & Install again
2. ticking the DrvCtrl40(with RunningOnWindows8point1 value)

But still remains the same.

![Snipaste_2020-02-29_20-45-22](https://user-images.githubusercontent.com/31816636/75607680-a00f3680-5b34-11ea-8884-beec33521ebd.png)
![Snipaste_2020-02-29_20-45-42](https://user-images.githubusercontent.com/31816636/75607682-a2719080-5b34-11ea-803b-b6d0635ad714.png)

**Comment by miaachan** [comment]
I tried several versions and finally find that 6.0.8898.1 does work.

Here is my steps:
1. Install 6.0.8898.1
2. Reboot
3. Everything won't work, until i do the step 4.
4. Manually change my audio device from Realtek driver to AAF Realtek one.
5. SB Connect 2 is now working great

But once rebooted, the SB Connect 2 shows "cannot detect audio devices" again.

What should i do? Thank you.

**Comment by gotexis** [comment]
i have the same issue :(
