### ISSUE TITLE
[Asus Z390-F Mobo] No 5.1 even after installing the drivers

### ISSUE THREAD

**Issue by dhananjay151293** [AlanFinotty1995/AAFRealtekMod#28]
Hello @AlanFinotty1995

First off, many many thanks for developing this mod!

I have an Asus ROG Z390-F motherboard with an optical out port available on the rear I/O panel. I have connected it to my Sony HT-RT3 that supports 5.1 surround sound, via a digital optical cable.

initially, I was under the impression that simply connecting my PC's optical out to my sound system's optical would give me 5.1 audio, however it didn't. Even after installing the audio drivers from Asus' page, it didn't work.

So, I started looking up to get it working when I came around your thread on TechPowerUp. The problem is, I can't register there for the reason that they are blocking registrations from certain countries.

Anyhow, I went ahead with the latest available driver of yours. And here's what I did:
1) Enabled 'developer mode' in Windows settings
2) Installed the drivers only without SB or Nahamic.
3) After the reboot, under the 'Sound' section in Control Panel, it shows the device as'Digital S/PDIF Out'.
4) I even changed the format (Properties > Advanced) to Dolby Digital Live (5.1 Surround), without any issues.

https://imgur.com/1gE2UXm
https://imgur.com/Exn8DK5

So I believe everything was installed correctly. But when I try testing the sound in (Properties > Advanced), it still plays from only the front 2 channels.

I also tried the instructions provided by you under the 'How to Activate Dolby Digital Live?' spoiler on the thread. But the 'Realtek Audio Device Tweak' shows the info as shown in the image below.

https://imgur.com/w6VezFM

Please, I really wanna get 5.1 running on my system. And I have no knowledge of audio/sound systems at all.

Can you help?

**Comment by AlanFinotty1995** [comment]
Open "Realtek Audio Device Tweak" and enter the values ​​for:

**Dolby Digital Live:**
PCI VID: 1458
Verb VID: 1458
SID: A102

**DTS Interactive:**
PCI VID: 1849
Verb VID: 1849
SID: 1151

**Comment by dhananjay151293** [comment]
Thanks a lot! I will try and report back.

**Comment by dhananjay151293** [comment]
@AlanFinotty1995 
I reinstalled the drivers with just 'Realtek Default Apo'.

Are these values correct? Do I have to put the VID and DID values as '0' or leave them as it is? (See the image please)
https://imgur.com/voVkXRl

Also, in the 'Realtek Audio Device Tweak' windows, there's 'HAS RTKDHAUD.DAT' flashing in red.

**Comment by dhananjay151293** [comment]
UPDATE: Got it working! Changed VID and DID to '0' as you showed in the spoiler on the thread. Rebooted the PC and tried playing a movie with 5.1. It worked!

Thanks a lot @AlanFinotty1995 You have done fantastic work.

I do have a question. When I open the Realtek Audio Device Tweak and Realtek HD Audio Monitor, they both detect my PC as Gigabyte, instead of audio. Is that normal?

**Comment by AlanFinotty1995** [comment]
> EDIT: If I try and open Realtek HD Audio Manager, it is not opening.

Open Windows Explorer, navigate to "**%program files%\Realtek\Audio\HDA**" and run "**RAVCpl64.exe**" or "**RtkNGUI64.exe**".

**Comment by AlanFinotty1995** [comment]
> I do have a question. When I open the Realtek Audio Device Tweak and Realtek HD Audio Monitor, they both detect my PC as Gigabyte, instead of audio. Is that normal?

This is due to the fact that the hexadecimal combination "**1458**" represents the motherboard manufacturer GIGABYTE. But it is normal.
