### ISSUE TITLE
Why? Removed Dolby Atmos in Windows 10

### ISSUE THREAD

**Issue by ghost** [AlanFinotty1995/AAFRealtekMod#3]
Please revert back to Dolby Atmos. And remove the Andrea enhancements.

**Comment by AlanFinotty1995** [comment]
From the next release, I will be returning to Dolby ATMOS.

**Comment by Wolfrisger** [comment]
I was wondering the same thing, for me Dolby ATMOS is the best and working one. looking for the next release, thanks :D
