### ISSUE TITLE
Laptop Headset Jack - No Sound/Mic

### ISSUE THREAD

**Issue by ZaTaisho** [AlanFinotty1995/AAFRealtekMod#33]
I have just did a complete wipe and reinstall to Windows 10, made sure I'm up to date on Windows Updates, and install some necessary files for programs to work correctly (such as Microsoft Visual C++ Redistributable).

However, after installing the latest updated AAF Realtek mod driver, everything seemed to work just fine, except for when using my laptop's headset jack. When I plug my headset into the jack, all audio that plays from the laptop is immediately silenced, but I still hear nothing from the headset & the microphone remains using my laptop's default mic instead. The Sound Control Panel says that it's playing audio just fine, but I can't hear a thing.

**Comment by RCCore** [comment]
Volume Mixer,Was the problem to all sound muted(In my case).

**Comment by RCCore** [comment]
For me when I talk in discord the slides in volume mixer just go up and down by himself.

**Comment by gebilaowang66662** [comment]
This kind of problem occurs when I install this kind of driver on my laptop.

**Comment by RCCore** [comment]
Make sure your laptop has a Realtek chip so you can go into the device manager and search for Sound, video and game controllers and it should write Realtek high definition audio device. (I hope it works for you)

**Comment by ZaTaisho** [comment]
> Make sure your laptop has a Realtek chip so you can go into the device manager and search for Sound, video and game controllers and it should write Realtek high definition audio device. (I hope it works for you)

What do you mean by "Write Realtek High Definition Audio"?
My Laptop does have a Realtek chip... I guess I'm not understanding as to what you want me to do in Device Manager.

**Comment by RCCore** [comment]
(https://user-images.githubusercontent.com/63298991/80978606-f6e40580-8e2e-11ea-9714-330881d11322.png) just watch the image

**Comment by ZaTaisho** [comment]
@RCCore Whatever it was, I did _another_ fresh install of Windows 10 on my laptop, making sure to wipe everything in the process, including all of my Microsoft Account history (since that seemed to be a culprit for other issues I've been having, such as User Permissions), installed all of the necessary files, such as Microsoft Visual C++ and the Redistributable files, as well as the Microsoft .NET Core SDK files... then installed the latest version of AAF Optimus Sound driver.

NOW it works like a charm. My headphone jack works perfectly now without issue!
(I haven't tried having DTS/Dolby work yet, but it works on the default install at the least)
