### ISSUE TITLE
Audiodevice cannot be detected Soundblaster

### ISSUE THREAD

**Issue by theowa1** [AlanFinotty1995/AAFRealtekMod#38]
![Unbenannt](https://user-images.githubusercontent.com/39044089/80100311-1302bf80-8570-11ea-9486-5f84a77df3e5.PNG)
I searched the whole forum for a solution found a few but none of them worked.
because a lot of people seem to have this problem can someone post the solution here (if there is one).

I you have the same problem as me just search with this link and try to find a properly working solution: https://www.techpowerup.com/forums/search/2073936/?q=Sound+blaster+fix&t=post&o=date

**Comment by theowa1** [comment]
THE SOLUTION: (pretty easy) just turn off your custom firewall and restart. works great

**Comment by gotexis** [comment]
@theowa1 what do you mean - i have the same issue but i dont use custom firewall
