### ISSUE TITLE
Drivers didn't install / change

### ISSUE THREAD

**Issue by xenon205** [AlanFinotty1995/AAFRealtekMod#4]
I installed your modded drivers but they didn't update my existingones and i can't change them manualy. Is there something wrong with this version ? (AAFDrvInst_HDA_ALL_AE-6.0.8854.1)

P.S. After few more atempts i ended up installing them but nahimic and SB connect are saying that my audio drivers are not compatible.
![Untitled](https://user-images.githubusercontent.com/14995106/70387893-f001b580-19aa-11ea-873a-cc342546b666.png)

**Comment by AlanFinotty1995** [comment]
Before installing this version, it is recommended that you uninstall any and all Realtek drivers on your system and, if possible, run a program to repair errors (eg Advanced SystemCare), then restart your pc and try again.

**Comment by xenon205** [comment]
I did as told, only diference is that Nahimic is not starting at all :)

**Comment by AlanFinotty1995** [comment]
Try the latest version (6.0.8888.1)
