### ISSUE TITLE
UI working fine....no effects are working in dolby,SBC2,realtek control panel

### ISSUE THREAD

**Issue by ANULAL2020** [AlanFinotty1995/AAFRealtekMod#40]
![Screenshot (2)](https://user-images.githubusercontent.com/64322146/80284761-0a5fe400-873e-11ea-992b-5a89e0e0dec5.png)
I am using the version 6.0.8924.1...Due to boot error i reinstalled windows on my pc....then i installed modded driver of you.on first time error occured with the keygen file while installing the driver...after i installed some c++ programmes the installation became sucess without any problem.then i restart my pc.When i opened the app, app opened without any problem...but when i changed the equaliser and another settings in SB,Dolby..but no change in effect occured ...
i follwed the instructions previously uploded y you...i changed the settings in driver policy...restarts many times..but result was waste...
please you can help me...why this occured in my pc....all the version worked before reinstalled my windows...
my realtek chip is alc887

**Comment by ANULAL2020** [comment]
After hardwork i got the answer.During installation process i did not selected nahimic app.this is the reason for nonworking effects in this app.if we does not select nahimic you cant change the  effect,it will work like a fake app.Alan bro..please check , if it is a bug please resolve the problem...

**Comment by RCCore** [comment]
When I first installed this sound mode I encountered almost the same error as you had installed my dolby, nahimic but I did not install my sound blaster and my equalizers did not work. So I do not think it is a bug you must have the whole package installed to make your sound work well.

**Comment by ANULAL2020** [comment]
OK... THANKS BRO...for your healthy answer... @RCCore **HAVE A GREAT DAY**
