### ISSUE TITLE
No sound at all

### ISSUE THREAD

**Issue by BennoMP** [AlanFinotty1995/AAFRealtekMod#41]
I'm not getting any sound and if I want to play the test tone in Windows settings I get an error (see image)
I'm using the Realtek ALC261 sound chip on a HP DC8000 Elite CMT PC. I have DrvCtrl40 enabled in the driver tweaking tool. I've tried downgrading to AAFHDAudioPack-6.0.8911.1, which worked for me but it's still not producing any sound and it's giving me the same error.
PS: I'm running Windows 10 Pro build 1909 (OS Build 18363.815)
![image](https://user-images.githubusercontent.com/61586142/80866187-b5682480-8c8d-11ea-9149-3aa9b6193180.png)

**Comment by AlanFinotty1995** [comment]
Try the most recent version (6.0.8924.1)

**Comment by programatix** [comment]
No sound for me too. I install version 6.0.8924.1.

Realtek® ALC1150 on ASUS Z87-PRO motherboard.

**Comment by BennoMP** [comment]
> Try the most recent version (6.0.8924.1)

I tried that. Same error. Could it be that Windows deleted some files that are needed? I read that the latest patch sometimes deletes files for no apparent reason.

**Comment by ANULAL2020** [comment]
go to windows/system32/driverstore/filerepository and then delete the files related on this mode.. In my pc these are the files folder name...
aafasioext.inf_amd64_1f409b57cf7d9b31, aafasioswc.inf_amd64_38766d892b43cd15, apodolbyext.inf_amd64_74fb33460818548e, apodolbyswc.inf_amd64_53b83bb3590673a8, aponh3ext.inf_amd64_b348ab09e1ecc631, aponh3swc.inf_amd64_b6510db63dd8b0af, aportkext.inf_amd64_6cdf183bce6cfe22, aportkswc2.inf_amd64_d10c37bf3d94d47d, aposbxext.inf_amd64_b07bc55972ca9730, aposbxswc.inf_amd64_cc46a47a76f90daf, hdx.inf_amd64_c09a3c5e5d4c0a70, 
Then go to device manager and uninstall the driver manually...(softwarecomponents , then aaf sound driver...
THEN uninstall the remaining realtek mooded driver with an uninstaller.(add or remove programme settings)...then restart pc and install again. I hope this will work.. if not modder AlanFinotty1995 shall help you...
![Screenshot (6)](https://user-images.githubusercontent.com/64322146/80909339-14d53b80-8d45-11ea-85d7-7ea9e08a4dd5.png)
![Screenshot (7)](https://user-images.githubusercontent.com/64322146/80909350-2b7b9280-8d45-11ea-922c-709bdb018505.png)

**Comment by BennoMP** [comment]
@ANULAL2020 that did the trick, thanks. Crab rave is playing back like a charm again :)
