### ISSUE TITLE
Audio Device

### ISSUE THREAD

**Issue by RCCore** [AlanFinotty1995/AAFRealtekMod#48]
In the Realtek HDA driver test utility, I have an error „Fail Service_Control_Stop on Audiosrv!!”
![image](https://user-images.githubusercontent.com/63298991/83062252-04c02b80-a067-11ea-8730-063ca19e2e54.png)

**Comment by AlanFinotty1995** [comment]
What exactly happened?

**Comment by RCCore** [comment]
Well I want to restart the driver i pressed the last button on the right and this is what happend

**Comment by RCCore** [comment]
*happened

**Comment by AlanFinotty1995** [comment]
Do you want to make any changes to your audio chip policy?

**Comment by RCCore** [comment]
No i dont want to make any changes but the last button on the right i think has the ability to restart the driver

**Comment by RCCore** [comment]
In the old version of your driver this button had the ability to restart the sound if a problem had accoured.

**Comment by AlanFinotty1995** [comment]
I saw that the error occurs in the Audiosrv service (Windows Audio Service). It may be the same when the audio device is being used by some program in the foreground or background.

**Comment by RCCore** [comment]
In my last attempt to resolve the problem I restarted the Windows Audio Service from Services

**Comment by RCCore** [comment]
And didnt solve the problem

**Comment by RCCore** [comment]
I dont know how to solve this problem

**Comment by RCCore** [comment]
If you want my Audio codec from my motherboard I can give it to you

**Comment by RCCore** [comment]
My motherboard is an ASUS Prime B360M-A with audio codec ALC887

**Comment by AlanFinotty1995** [comment]
Are you having a problem with your PC's audio?

**Comment by RCCore** [comment]
No all the programs are working fine

**Comment by RCCore** [comment]
But this error show up every time when I open my PC the Realtek Manager is not showing up

**Comment by RCCore** [comment]
I need to enable the Audio Manager from this program every time I open my Computer

**Comment by AlanFinotty1995** [comment]
Is it not booting automatically with the system?

**Comment by RCCore** [comment]
Nope

**Comment by RCCore** [comment]
I searched every location possible for residue from my old Realtek driver but I found nothing

**Comment by AlanFinotty1995** [comment]
The registry key required for such initialization must be missing or duplicated. Go to "**HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Run**" and send me an image, please.

**Comment by RCCore** [comment]
![image](https://user-images.githubusercontent.com/63298991/83064793-0ee42900-a06b-11ea-8e5f-3f93ca05e8d2.png)

**Comment by RCCore** [comment]
It is ok?

**Comment by AlanFinotty1995** [comment]
Delete the "RtkAudUService" entry

**Comment by RCCore** [comment]
I deleted it

**Comment by RCCore** [comment]
![image](https://user-images.githubusercontent.com/63298991/83065041-78fcce00-a06b-11ea-8f41-ffa4d55af478.png)

**Comment by AlanFinotty1995** [comment]
Try again

**Comment by RCCore** [comment]
I need to restart my computer?

**Comment by AlanFinotty1995** [comment]
Or do one of these lines:
**"%programfiles%\realtek\Audio\HDA\ravcpl64.exe"**
**"%programfiles%\realtek\Audio\HDA\RtkNGUI64.exe"**

**Comment by RCCore** [comment]
I still get Fail Service_Control_Stop on Audiosrv!! error

**Comment by RCCore** [comment]
but the Realtek manager is working

**Comment by RCCore** [comment]
You think I should try to restart Windows Audio Service again to see it is working?

**Comment by RCCore** [comment]
I have another question what is AFF Extra ASIO?

**Comment by AlanFinotty1995** [comment]
> I have another question what is AFF Extra ASIO?

It is an independent ASIO driver. Its installation is optional. It is useful for those who use music editing software (ACID) and video (VEGAS).

**Comment by RCCore** [comment]
The error still persist after the restart of Windows Audio service

**Comment by RCCore** [comment]
I resolved the problem apperently the issue about Windows Audio service was it has been used by the Armoury Crate from Asus and the service name is (Lighting Service) you need to stop the service and then disable it and its DONE (Thanks for The help Sir, Keep up the good work)

**Comment by AlanFinotty1995** [comment]
> I resolved the problem apperently the issue about Windows Audio service was it has been used by the Armoury Crate from Asus and the service name is (Lighting Service) you need to stop the service and then disable it and its DONE (Thanks for The help Sir, Keep up the good work)

Thanks for the feedback!!
