### ISSUE TITLE
6.0.8960.1 // Not Working Sound Blaster & A-Volute Sonic Studio 3 (ASUS ROG)

### ISSUE THREAD

**Issue by apk1995apk** [AlanFinotty1995/AAFRealtekMod#53]
Hi Alan ! 

Thanks for your mod.
I recently updated to latest release 6.0.8960.1. But some apps did not work/launch.

Selected below packages to Install -> 
**Dolby Atmos** -> _Works fine_
**Sound Blaster 720** -> _Installed, does not launch_
**A-Volute Sonic Studio 3 (ASUS ROG)** -> _Installed, does not launch_

Noticed that Sound Blaster app process goes to suspended state every time it is launched.
Sonic Studio 3 shows driver error. 
Tried & verified even if single app is installed they both don't run.

Win 10 Ver: 1909, OS Build 18363.693
Realtek Chipset : ALC892

![foobar2000_SkQm2e29FA](https://user-images.githubusercontent.com/10492511/84514249-5532bc80-ace8-11ea-9a2b-ddb137f57b45.png)

**Comment by ANULAL2020** [comment]
I am also facing this problem....
I installed many times ,but not solved the problem...
I uninstalled sound blaster manually, after that sonic studio works well ...THEN AGAIN INSTALLED sound blaster ..but the result was bad.... the process of restart works well...
CHIPSET ALC887... win 10 1909 18363.900 

PLEASE give me suggestions from any users.. installed version is 6.0.8960.1
![Screenshot (12)](https://user-images.githubusercontent.com/64322146/84674725-f1f39500-af48-11ea-81a8-81a9a3dd2719.png)

**Comment by RCCore** [comment]
I don't think it has to do with your PC, for example I have ALC887 as an audio codec and I think it is not 100% supported, because I had the driver installed and actually there were moments when it worked and then it stopped working. (We have to wait for another driver update.)

**Comment by apk1995apk** [comment]
Closing this issue. Problem solved with installation of AAF_DCH_RealtekModded drivers.

[](https://github.com/AlanFinotty1995/AAF_DCH_RealtekModded/releases)

![foobar2000_KgrrRJKCmY](https://user-images.githubusercontent.com/10492511/85009608-534f7a00-b17c-11ea-80e6-21e9e52b9bb0.png)
