### ISSUE TITLE
Theres even no guide to install it, it doenst work.

### ISSUE THREAD

**Issue by enescaglayan** [AlanFinotty1995/AAFRealtekMod#6]
Today i installed the latest version of this "modded" thingy on my fresh installation and just installed connect 2 *720 and probably the realtek driver(I know it will work on my sound card because my oem provided me sound blaster 3 in my laptop's driver web page and it worked perfectly.)

When i restarted my computer blaster was installled saying my audio card is unsupported also when i click the sound tray icon it opens diagnostic troubleshoot wizard because it doesnt have any audio devices "installed". So i opened device manager and i installed your modded realtek driver then i restarted my computer.

This time connect 2 *720 detected my device but there was no sound at all. Then i tried switching to regular realtek driver, connect 2 *720 this time again detected it but there was no sound effect to my sounds, so i again switched to your modded driver and restarted my computer, it was the same, connect 2 detected it but there was no effect on to my sounds.

I just want a guide how to install it just how, making a installer isnt enough. I just want better sound and nothing else i dont know anything about the sounds anyway.

**Comment by enescaglayan** [comment]
*360 is the same

**Comment by Sapphiress** [comment]
Uninstall the modded package and any other sound drivers you have with revo using moderate setting, Restart, Right Click and Run the installer as admin, Uncheck Nahimic(Helped when I had a similar issue). reboot right when it asks you too and that should fix it.

**Comment by AlanFinotty1995** [comment]
I apologize for the delay, I ran out of internet at my residence, but I have already released a more updated driver package, with several improvements.

**Comment by enescaglayan** [comment]
I'm closing issue for now because i think sound blaster 3 is enough for me currently, sorry for disturbing will reopen if i try to reinstall and fail.

Also please make guides for these things, like I don't even know what is my audio codec or whatever its called. I like how you make the installer thingy to make it easier for us but i think its not enough.
