### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by Osiris-Team** [AlanFinotty1995/AAFRealtekMod#63]
I want to upgrade to AAF DCH Optimus Sound but I cant remove the old version...

**Comment by RCCore** [comment]
What cant you uninstall from your old version the program or the drivers?

**Comment by Osiris-Team** [comment]
> What cant you uninstall from your old version the program or the drivers?

I dont even know, what exactly I should remove...

**Comment by RCCore** [comment]
What kind of error do you get when you are trying to uninstall from the control panel?

**Comment by RCCore** [comment]
Oh :)))

**Comment by RCCore** [comment]
No problem it happens

**Comment by Osiris-Team** [comment]
@RCCore 
Ok I do got another issue. I managed to uninstall the old version and now I installed AAFAudioPackDCH-6.0.8984.1.
But this is the result:
<img src="https://i.imgur.com/bO7dfrr.png">
Also soundblaster connect and sonic studio 3 arent working and I have no clue where dolby atmos is.

**Comment by RCCore** [comment]
I had the same problem, but if you go to the driver policy in the drvcontrol40 you will see an option with RunningOnWindows8point1 just check the drvcontrol40 as the image below 
![image](https://user-images.githubusercontent.com/63298991/89181315-1e687c80-d59c-11ea-8e51-6f100608d4ac.png)

**Comment by RCCore** [comment]
For the Dolby Atmos I think you can get it from the Microsoft Store

**Comment by AlanFinotty1995** [comment]
More information in 1st TechPowerUp thread page.

**Comment by RCCore** [comment]
@AlanFinotty1995 you are the best, and for all your work I have to say THANK YOU. (From Romania)

**Comment by epman100** [comment]
> 
> 
> For the Dolby Atmos I think you can get it from the Microsoft Store

there are 3 other different editions of "Dolby Atmos" apps from the MS store such as Dolby Atmos for Gaming (I use that one on Gigabyte systems like my Gigabyte board), Dolby Atmos Sound System & Dolby Atmos Speaker System.

the AAF DCH Optimus Sound drivers use the normal Dolby Atmos app.
