### ISSUE TITLE
6.0.8854.1 Nahimic does nothing

### ISSUE THREAD

**Issue by xenon205** [AlanFinotty1995/AAFRealtekMod#9]
6.0.8854.1 Nahimic doesn't work... it start's normaly, no error, yet turning on or off or changing settings doesn't do anything

**Comment by AlanFinotty1995** [comment]
I apologize for the delay, I ran out of internet at my residence, but I have already released a more updated driver package, with several improvements.

**Comment by AlanFinotty1995** [comment]
Try the latest version (6.0.8888.1)
